### ISSUE TITLE
Add ranking info to Chrome Status dashboard

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#482] opened 2021-11-06 16:59 UTC
The [Blink feature usage](https://datastudio.google.com/u/0/reporting/1M8kXOqPkwYNKjJhtag_nvDNJCpvmw_ri/page/tc5b) dashboard embedded on chromestatus.com is sourced from HTTP Archive's `blink_features` dataset. It would be useful to slice the feature data by rank (site popularity).

**Comment by max-ostapenko** [comment] 2024-10-18 22:44
Duplicate of https://github.com/HTTPArchive/dataform/issues/25

**Closed by max-ostapenko** 2024-10-18 22:44 UTC
Labels: enhancement
